'use client';

import { useState } from 'react';
import { Sparkles, Copy, Check, RefreshCw } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { toast } from 'sonner';

interface AiSummaryPanelProps {
  summary: string;
  updatedAt: Date;
  onRefresh: () => void;
  isRefetching: boolean;
}

export function AiSummaryPanel({ summary, updatedAt, onRefresh, isRefetching }: AiSummaryPanelProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(summary);
      setCopied(true);
      toast.success('Summary copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch (_err) {
      toast.error('Failed to copy summary');
    }
  };

  const timeAgo = formatDistanceToNow(updatedAt, { addSuffix: true });

  return (
    <section className="relative w-full mb-xxl">
      {/* Glow Effect */}
      <div className="absolute -top-12 -left-8 w-64 h-64 bg-primary/10 rounded-full blur-[120px] pointer-events-none"></div>
      
      <div className="relative bg-surface-container-low/40 backdrop-blur-xxl rounded-xl p-xl lg:p-xxl border-t border-white/10 shadow-xl overflow-hidden">
        <div className="flex flex-col gap-lg max-w-4xl relative z-10">
          
          <div className="flex flex-wrap items-center justify-between gap-md mb-md">
            <div className="flex flex-wrap items-center gap-md">
              <div className="px-md py-xs rounded-full border border-primary text-primary flex items-center gap-sm bg-transparent">
                <Sparkles size={12} />
                <span className="font-label-caps text-[10px] uppercase tracking-widest">Generated by Gemini</span>
              </div>
              <span className="font-data-md text-data-md text-on-surface-variant/40">— Generated {timeAgo}</span>
            </div>
            
            <div className="flex items-center gap-sm">
              <button 
                onClick={handleCopy}
                className="flex items-center gap-sm px-md py-xs rounded-lg hover:bg-surface-container-high text-on-surface-variant hover:text-on-surface transition-colors"
                title="Copy Summary"
              >
                {copied ? <Check size={16} className="text-primary" /> : <Copy size={16} />}
                <span className="font-label-caps text-[10px] uppercase tracking-widest hidden sm:inline">Copy</span>
              </button>
              <button 
                onClick={onRefresh}
                disabled={isRefetching}
                className="flex items-center gap-sm px-md py-xs bg-surface-container-high rounded-lg hover:bg-surface-container-highest text-on-surface transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <RefreshCw size={16} className={isRefetching ? "animate-spin" : ""} />
                <span className="font-label-caps text-[10px] uppercase tracking-widest hidden sm:inline">
                  {isRefetching ? 'Generating...' : 'Generate New Insight'}
                </span>
              </button>
            </div>
          </div>

          <div className="mt-md">
            <div className="font-headline-md text-headline-md text-on-surface leading-relaxed whitespace-pre-wrap">
              {summary}
            </div>
          </div>
          
        </div>
      </div>
    </section>
  );
}
